repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.5
    hooks:
      - id: clang-format
        args: [--style=file]

  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.2.0
    hooks:
      - id: clang-tidy
        args: [-p=build]
